### ISSUE TITLE
Bug report: Unexpected token in JSON.parse

### ISSUE THREAD

**Issue by OmgImAlexis** [stoe/xo-action#13]
**Describe the bug**
```
✖  fatal     SyntaxError: Unexpected token u in JSON at position 0 
     at JSON.parse (<anonymous>)
    at Toolkit.run (/entrypoint.js:31:25)
    at Function.<anonymous> (/node_modules/actions-toolkit/lib/index.js:107:31)
    at step (/node_modules/actions-toolkit/lib/index.js:43:23)
    at Object.next (/node_modules/actions-toolkit/lib/index.js:24:53)
    at /node_modules/actions-toolkit/lib/index.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/actions-toolkit/lib/index.js:14:12)
    at Function.Toolkit.run (/node_modules/actions-toolkit/lib/index.js:98:16)
    at Object.<anonymous> (/entrypoint.js:5:9)
##[error]Docker run failed with exit code 1
```

**To Reproduce**
Have `xo` throw an error that's not accepted by `JSON.parse`.

**Expected behavior**
The correct error to be logged.

**Additional context**
Looks like this line is the culprit.
https://github.com/stoe/xo-action/blob/2ff5b825dcefe91cc3b4457b7566d53cae2e2a39/entrypoint.js#L31

**Comment by stoe** [comment]
@OmgImAlexis, thank you for opening.

Currently I don't have much bandwidth to look into this, but if you'd like to take a 🔪stab, PRs are always welcome.

🐙🐱💖

**Comment by OmgImAlexis** [comment]
Still an issue.
